### ISSUE TITLE
Pronunciation element gets added erroneously

### ISSUE THREAD

**Issue by rmlockwood** [sillsdev/web-languageforge#135] opened 2017-06-29 19:03 UTC
When I edit the note field in my Swedish project in LF and synchronize and look at the entry in FLEx, the pronunciation element has been added as a blank element. This may be related to #131.

**Comment by rmunn** [comment] 2017-06-30 04:11
Yes, this is caused by the same issue as #131, and should be resolved by the same bugfix. I'll mark this issue as a duplicate so we know to close it when #131 is closed.

**Comment by rmunn** [comment] 2017-07-13 04:40
Closing since the bugfix for #131, which should fix this issue, has been deployed to the live servers now. Please re-open if the issue persists.

**Closed by rmunn** 2017-07-13 04:40 UTC
Labels: duplicate
