### ISSUE TITLE
Fields showing up in SBF project for contributor that shouldn't

### ISSUE THREAD

**Issue by rmlockwood** [sillsdev/web-languageforge#160] opened 2017-09-05 13:43 UTC
Two custom fields at the entry level (Use Standard Spelling & VParadigm3SgPast), a custom field at the sense level (SimilarPhrase) and the POS field are all turned off for being visible to a contributor yet they are still showing.

**Comment by rmunn** [comment] 2017-09-07 08:48
I've found the cause of this bug — a mistake in how we filtered out fields that were turned off in the project configuration — and written a bugfix for it. We'll test the fix, then we'll close this issue once the bugfix has been deployed to the Language Forge site.

**Comment by megahirt** [comment] 2017-09-10 03:24
Thanks again for the bug report. This fix has now been shipped to languageforge.org In some cases I recommend doing a Ctrl-F5 in case the changes are not immediately reflected in your browser.

**Closed by megahirt** 2017-09-10 03:24 UTC
Labels: bug
