### ISSUE TITLE
Extra fields get removed from user's view unless "Show Extra Fields" is toggled on

### ISSUE THREAD

**Issue by longrunningprocess** [sillsdev/web-languageforge#1164] opened 2021-09-20 20:00 UTC
**Describe the bug**
I came to a word and wanted to change the "CV Pattern" to something else but it disappeared before I could type anything.

**To Reproduce**
1. Go to a word with a "hidden" field already populated
2. Click on the value in that field
3. Hit delete
4. The field immediately disappears

**Expected behavior**
If a person is editing a hidden field (and the user has the hide extra fields option on at the time), the field should continue to be shown long enough for the user to change the value.  OR, "hidden" fields should not be shown just because they contain a value, they should either be shown or hidden solely based on whether the user is showing or hiding extra fields.

**Screenshots**

https://user-images.githubusercontent.com/4412848/134066876-c7bc72e0-cd2a-4166-9aa2-539530dbe1cb.mov

**Comment by alex-larkin** [comment] 2021-09-21 04:11
In FLEx the user has these options for fields:
-  Always hidden
- Always hidden unless it contains a value*
- Always visible

I think this is a really great way of approaching field visibility. What do you all think? Would this transfer well to LF?

*Stays visible as long as the field is active, even if completely erased for a moment.

**Comment by longrunningprocess** [comment] 2021-09-21 12:59
I do think that could translate well to LF but it will come at a cost of some added complexity.  This is an area I'd like to make sure the effort and complexity is warranted for our users.  If/when this becomes a priority I'd like to have some in-person discussion.

**Comment by alex-larkin** [comment] 2021-09-21 13:06
Yes that is the constant tension 😃. Sounds good.

**Comment by longrunningprocess** [comment] 2021-09-21 14:28
no doubt, the "iron triangle", the "triple constraint"...  it's with us until the end!

**Comment by megahirt** [comment] 2021-10-01 04:44
This is exactly how the fields in LF are already designed.  We modeled it after FW visibility.  What @longrunningprocess is reporting here is that the field disappears instantly as soon as it doesn't contain a value - and this is bad UX.  We should do what @alex-larkin notes and don't make the field disappear until the field loses focus at a minimum.

**Comment by megahirt** [comment] 2021-10-01 04:53
probable duplicate of #1057

**Comment by megahirt** [comment] 2022-02-14 04:25
Closing as duplicate

**Closed** 2022-02-14 04:25 UTC
Labels: bug, duplicate, good first issue
