### ISSUE TITLE
LSA: <br/> added to the end of entries

### ISSUE THREAD

**Issue by darcywong00** [sillsdev/web-languageforge#59] opened 2017-01-13 10:38 UTC
From LSA 2017 user Elliot

I’m getting a `<br/>` added to the end of some entries after they are edited in languageforge and synced to FLEx.

**Comment by megahirt** [comment] 2017-09-07 02:27
Closing as a duplicate of https://github.com/sillsdev/web-languageforge/issues/134

**Closed by megahirt** 2017-09-07 02:27 UTC
Labels: bug
