### ISSUE TITLE
RTL text in the search box gets obscurred

### ISSUE THREAD

**Issue by rmlockwood** [sillsdev/web-languageforge#21] opened 2015-05-19 06:52 UTC
See graphic below:

![image](https://cloud.githubusercontent.com/assets/7088137/7697042/0f7549bc-fe04-11e4-9d0f-8dfe60e94e99.png)

This on the opening page and x is on the right side where RTL text gets typed.

**Comment by darcywong00** [comment] 2016-08-26 08:18
Duplicate of https://github.com/sillsdev/web-languageforge/issues/33

**Closed by darcywong00** 2016-08-26 08:18 UTC
Labels: duplicate
