### ISSUE TITLE
S/R: Blank picture appeared on entry after sync with LF if FLEx delete the picture.

### ISSUE THREAD

**Issue by dinakaranr** [sillsdev/web-languageforge#44] opened 2016-09-01 08:14 UTC
Steps to reproduce: This behavior appear when follow scenario 2 from test plan doc on “S/R Testing 0.9.42” tab
LanguageDepot_Project: India TestLangProj 05 ID: test-inda-tlp-05
Prerequisites:
LF 0.9.42 and FLEx “India TestLangProj 04” project have a picture in an entry.

FLEx User: Window 8.1 OS
1) Select an entry. the entry have picture and caption field have name
2) Delete that picture and S/R sync to LanguageDepot

LanguageForge User: Window 7 OS
1) Select an entry(Which have picture and used/edited by FLEx user)
2) Modified the “Picture Caption” name in the field.(changed to en: English)
3) S/R sync to languageDepot
4) After sync is completed. There is no picture appear and caption field have name which modified by LF user.

FLEx User: Window 8.1 OS
1) S/R sync to languageDepot. Here, There is no picture appear in an entry but picture caption appeared. So, I just clicked the Picture field on label to lead green crash.

Please refer screenshot for this in 31st August 2016 google doc. the issue number is 1 from below link. 
https://docs.google.com/document/d/1uetHFquLX5R6WI91GJjYQVD4s4JrS0CVQwPJpl6qsM4/edit

**Comment by irahopkinson** [comment] 2016-09-02 01:42
To clarify, the referenced scenario 2 is where FLEx deletes a picture and LF edits a picture field of the same picture causing a merge conflict.

**Comment by irahopkinson** [comment] 2016-09-02 02:09
This is a duplicate of https://github.com/sillsdev/web-languageforge/issues/39

**Closed** 2017-05-27 06:50 UTC
