### ISSUE TITLE
order of entries in the list

### ISSUE THREAD

**Issue by rmlockwood** [sillsdev/web-languageforge#16] opened 2015-05-07 07:31 UTC
In my Farsi project, the entry order seems to be messed up. This is the order I expected. (starting with the entries that have something in the fa writing system)
![image](https://cloud.githubusercontent.com/assets/7088137/7510391/b8fa9252-f49b-11e4-90a6-7c64c32a5fee.png)

The third one should have an equals sign (ا=)

**Comment by megahirt** [comment] 2015-05-11 03:11
Thanks for bringing the sorting problem up.  The initial version of Language Forge has no special sorting logic built in to handle non-Roman scripts and locale-specific sort rules.  A dumb sort is used based upon the numeric value of the Unicode code point, which is the simplest way to compare two characters.  Naturally, we want to get sorting right, so this will be a priority to fix in the future.  I'm uncertain as to how easy the fix will be, but will look into it.

**Comment by rmdiamondl** [comment] 2015-05-11 09:26
If it is just sorting by unicode values, it should do Arabic script as well. I don't need a special sort order.

**Comment by megahirt** [comment] 2015-05-11 09:29
I'm not a sort expert, but my initial investigations is that the code we are currently using won't get much right outside of the English language.  We need to utilize the ICU library which includes collation rules for locales.  Right now we're not doing that and that's why the output you're seeing is sorting funny.

**Comment by makerling** [comment] 2016-05-13 10:10
Hi, I'm preparing for a workshop session on Languageforge and in my preparations I noticed a bug that occurs relating to sort order. I'm not sure if improvements have been made to the issue above, but I'm posting it here as it appears to be similarly related.

**Steps to reproduce:** (My username on languageforge is bluedragon). I created a new project from a FLEx lift file of approximately 1242 entries. The initial sort order is OK. I created a new entry and then clicked back to list. This time the order is jumbled and in no particular order. When I try to create another entry, the left hand side column list of entries shows the same jumbled order. I tried clicking around several areas as well as logging out and logging in to see if the Dictionary Download triggered the proper sort. I also tried Chrome, Chromium, Firefox to see if there were any changes. I cannot get the original sort order back. I also tried creating a new project, did not import a .lift file and manually created 4 entries. After creating those 4 entries with only ASCII characters, it still jumbles the sort order (see attached image). 

![image](https://cloud.githubusercontent.com/assets/12460083/15244499/2247d8c6-190a-11e6-89ab-bad236dc5f56.png)

![image](https://cloud.githubusercontent.com/assets/12460083/15244764/7035ec84-190b-11e6-9d2c-60ccda4bb70c.png)

**Comment by megahirt** [comment] 2016-05-14 03:54
Hi makerling,

Thanks for reporting this bug.  It looks like we have a different bug that you are experiencing (jumbled sort order for latin script), so I'll copy your report into a new bug.

**Comment by megahirt** [comment] 2016-05-20 10:08
Hi makerling,

The fix for #32 has been shipped to languageforge.org  Please do let me know if the issue persists.  Thanks for reporting it.  You may need to refresh your browser (F5) in some instances to get the updated code.

Thanks,

Chris

**Comment by megahirt** [comment] 2016-05-20 10:09
Ron,

Can you confirm that your sort issue is fixed as well?

Thanks,

Chris

**Comment by rmlockwood** [comment] 2016-05-20 16:46
In the quick glance I made, it looks like it is working.

 

Ron

**Comment by megahirt** [comment] 2016-06-24 04:11
This sorting issue is essentially a duplicate of #32.  Closed as resolved since #32 is resolved.

**Closed by megahirt** 2016-06-24 04:11 UTC
Labels: bug
