### ISSUE TITLE
Etymology element erroneously created

### ISSUE THREAD

**Issue by rmlockwood** [sillsdev/web-languageforge#131] opened 2017-06-27 23:52 UTC
I'm using 8.3.8 with my Swedish project now and it seems that every time I edit an entry in LF and synchronize to my FLEx application, an empty etymology element gets created in my entry. The etymology element has a bunch of fields that are visible filling up most of my entry view. I have to delete the etymology element to get rid of it.

**Comment by rmunn** [comment] 2017-06-28 09:42
This is probably a bug in the send/receive process; I'll look into it.

**Comment by rmunn** [comment] 2017-06-28 10:01
I just wrote what I believe to be a fix for this bug. I'll test it over the next couple of days, then close this issue once we've confirmed that the bugfix works.

**Comment by rmunn** [comment] 2017-07-13 04:39
We've deployed the bugfix to the live servers, so this bug report can be closed. @rmlockwood, if you do a Send/Receive on Language Forge, the erroneously-added Etymology elements should go away. (And the same for the Pronunciation elements discussed in #135). If you discover that a Send/Receive does *not* delete the empty Etymology elements, then please re-open this issue since that would mean that the bug is not yet fixed.

**Closed by rmunn** 2017-07-13 04:39 UTC
Labels: bug, Sync feature
