### ISSUE TITLE
S/R fails in FLEx after doing an update in LF

### ISSUE THREAD

**Issue by PaulNel** [sillsdev/web-languageforge#156] opened 2017-09-05 01:55 UTC
![sr failure after update in lf](https://user-images.githubusercontent.com/17054082/30041831-c199d948-91b2-11e7-991a-5d3061806b9d.png)

I did a SR of the Hrê FLEx project in LF. When going back to FLEx 8.3.9 to pick up the changes. I get a stream of messages, "Warning: Pull data chunk failed: The request was aborted: The request was cancelled. Warning: Pull data chunk failed"

Expect that SR for project in either FLEx or LF should work without issue and reflect changes to sync data without error.

**Comment by megahirt** [comment] 2017-09-05 05:10
Hi Paul,

I'm sorry you got this error in FLEx/FlexBridge.  It appears to me that LanguageDepot was not responding properly, although the log doesn't contain enough information to say for sure.  This could have been caused by a variety of network or server issues, but at the moment I am able to clone your project and open it just fine in FW 8.3.9.  Can you try the S/R again in FLEx?  Also, if you continue to have problems perhaps deleting the project in FLEx and doing a get project from colleague would clear out this error.  I can see that the Language Forge edits came into FLEx just fine.  I can see that one entry was modified (see TortoiseHg screenshot below):
![image](https://user-images.githubusercontent.com/3444521/30046082-4869a2b2-9232-11e7-94ff-aa4cf887d586.png)

I can also see that the changes you made in LF made it into FLEx:
![image](https://user-images.githubusercontent.com/3444521/30046172-d0dc35f6-9232-11e7-90b8-30cc7eed52e1.png)

Alas, your edits have encountered a different bug where HTML elements are leaking into the FW data, and that is being tracked with this bug:  https://github.com/sillsdev/web-languageforge/issues/136  My apologies.  The workaround when doing cut/paste is to first paste the text into a plain text editor like Notepad before pasting back into LF.

I'm closing this bug but feel free to re-open if you are still having S/R issues.

**Closed by megahirt** 2017-09-05 05:10 UTC
