### ISSUE TITLE
Sense level custom fields not importing

### ISSUE THREAD

**Issue by rmdiamondl** [sillsdev/web-languageforge#18] opened 2015-05-07 07:39 UTC
In my Swedish project only one of the custom fields at the sense level shows up (Target Equivalent), the other called Target Sense Number doesn't show up. In my Farsi project, however, I see two custom fields I created at the sense level. In both projects, I'm not getting the data that should be in those fields. In the Farsi project I see data for the entry level custom fields.

**Comment by megahirt** [comment] 2015-05-11 04:15
Ron,

Thank you for reporting this.  Can you try to re-import the data into a new separate project and see if the problem is fixed?  I have a hunch that the data was imported using older (buggy) code that is now fixed.  If after importing into a new project you have the same issue please reply to this issue and we will look into it and fix it.

Thanks.

**Comment by rmdiamondl** [comment] 2015-05-11 09:17
I just tried importing into the project Swedish2. It still doesn't show me the custom field data. An example of the data in the Target Equivalent field is: silfw://localhost/link?app%3dflex%26database%3dEnglish-BYU-FlexTrans%26server%3d%26tool%3dlexiconEdit%26guid%3d1134bbac-bc4d-4d6d-b5b2-69302e5741c8%26tag%3d

**Comment by megahirt** [comment] 2015-05-11 09:53
Hi Ron,

I am seeing what you are seeing.  Can you email me with a dropbox link of your data (FW LIFT export zip) so I can fix the import script?

Thanks!

**Comment by rmdiamondl** [comment] 2015-05-11 09:59
Here are links to my two lift zip files: https://www.dropbox.com/s/89e39rynik7x0wh/Farsi-LIFT.zip?dl=0

https://www.dropbox.com/s/qwxnomt9r8zizga/Swedish.zip?dl=0

 

Ron

**Comment by megahirt** [comment] 2015-05-12 03:30
Thanks Ron.  I now have your data and will update you when we have a fix.

**Comment by irahopkinson** [comment] 2015-05-19 03:14
I just looked directly in the Swedish LIFT file. You aren't seeing the **Target Sense Number** because none of the 580 entries exported have that item in the data (so we can't import it). If the data is there in FLEx then it may not be exporting it to LIFT. When exporting, ensure *Full Lexicon LIFT 0.13 XML* is selected (although I'm sure your already doing this as the other custom field shows up).

**Closed** 2015-05-19 05:19 UTC

**Comment by rmdiamondl** [comment] 2015-05-19 06:42
Ok, but you only "solved" one of the issues. The custom field Target Equivalent doesn't have any data in it and it should. The entry with gloss "boy" would be an example of an entry with data in that field. Thanks, Ron

**Comment by rmdiamondl** [comment] 2015-05-19 06:45
Just checked and I'm seeing the data there now. Problem solved, I guess.

**Comment by irahopkinson** [comment] 2015-05-19 07:11
Sorry, I didn't make it clearer. There were two issues: I commented about
the first one (no data to import), then later pushed a fix for the other
(data not displaying).

On Tue, May 19, 2015 at 6:45 PM, rmdiamondl <notifications@github.com>
wrote:

> Just checked and I'm seeing the data there now. Problem solved, I guess.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sillsdev/web-languageforge/issues/18#issuecomment-103368820>
> .
>



-- 
Ira Hopkinson

SIL International Language Software Development, PaLaSo <http://palaso.org/>
