### ISSUE TITLE
Word not findable in LF even though it's there

### ISSUE THREAD

**Issue by rmlockwood** [sillsdev/web-languageforge#112] opened 2017-05-19 02:46 UTC
In my Swedish LF project I have the word dö. When I type this in the search box it doesn't show me the word.

**Comment by Nateowami** [comment] 2017-05-19 02:50
This sounds like an issue with the search functionality. Is it possible your other issue (#111 unable to find the word stör) may also be an issue with search? Do Language Forge and FLEx show the same number of words in the dictionary?

**Comment by rmlockwood** [comment] 2017-05-19 02:57
in 111, the word doesn't show when I scroll through the list. This one dö does show in the list.

**Comment by rmlockwood** [comment] 2017-05-19 03:49
Actually it is the same issue. I closed 111.

**Comment by rmunn** [comment] 2017-05-19 07:39
I would guess that the issue is composed vs. decomposed characters. @rmlockwood, which keyboard layout are you using to type the ö character? Depending on whether your keyboard layout is configured to produce composed or decomposed characters, it might be typing a single ö character (the "composed" form of ö) into the search box, or it might be typing an o followed by the combining-umlaut character (the "decomposed" form of ö). Both of these will look like ö on screen, but internally they are two different representations.

So it looks like the root cause of this LF bug is that we don't yet handle composed and decomposed characters properly. We should be able to handle both composed and decomposed input in the search box, and apparently we aren't handling that yet.

**Comment by megahirt** [comment] 2017-05-19 09:52
That's correct.  We do not yet correctly handle composed/decomposed
characters when searching.  This is a bug that needs fixing.

**Comment by rmlockwood** [comment] 2017-05-19 15:50
Yes, that seems to be the problem. I think FLEx stores everything decomposed and all European keyboards that I know of will do umlaut characters as composed.

**Comment by megahirt** [comment] 2017-05-23 02:11
This is a duplicate of sillsdev/web-languageforge#64

**Comment by rmlockwood** [comment] 2017-06-15 15:18
I saw this is marked as closed. Does that mean it should be working currently in LanguageForge? It doesn't seem to be. Thanks.

**Comment by Nateowami** [comment] 2017-06-15 15:32
@rmlockwood  The necessary changes have been made, but they're not yet active on the website. It's difficult to predict when they will be. My understanding is that issues are supposed to remain open until the changes are active on the website, so I'll reopen this. Correct me if I'm wrong @irahopkinson.

**Comment by rmunn** [comment] 2017-06-15 15:40
The reason it was closed is because when the fix was committed into the source repository, the commit message contained the text "Fix (bug number)". When GitHub sees that text in a commit, it *automatically* closes that bug report, without asking. So when Ira committed the fix, GitHub automatically closed the bug report, even though the fix hasn't yet been deployed to the live site. (For any change to the site, we go through a few days of testing before we make the change live). Since we haven't yet deployed the fix, @Nateowami was right to reopen the issue. Thanks!

**Comment by irahopkinson** [comment] 2017-06-16 07:46
@rmlockwood sorry about closing this prematurely and thanks for re-opening @Nateowami. I've added an item to our shipping card so we will close this again once it is shipped to live. At that point issue https://github.com/sillsdev/web-languageforge/issues/116 will also be fixed.

**Comment by megahirt** [comment] 2017-06-29 08:40
@rmlockwood thanks for your patience and for reporting this issue.  We've shipped a bugfix that is now on languageforge.org so I will close this issue.

**Closed by megahirt** 2017-06-29 08:40 UTC
Labels: duplicate
