### ISSUE TITLE
No response when clicking on gear icon in narrow view of site

### ISSUE THREAD

**Issue by rmlockwood** [sillsdev/web-languageforge#151] opened 2017-08-29 07:02 UTC
I noticed first on my iPhone that clicking on the gear icon wasn't doing anything. I then tested it in Chrome and found the same thing happens when I have the browser only taking up part of the screen. It seems to happen when the screen is narrow enough that the hamburger shows up on the upper left.

**Comment by megahirt** [comment] 2017-08-29 09:13
Thanks Ron for submitting this.  I have seen this behavior as well.  We'll
take a look at it.

**Comment by rmunn** [comment] 2017-08-29 09:59
Took a quick (very quick) look, and found the following:

* The Settings menu (the gear icon) is represented by an HTML `div` with the CSS classes `btn-group dropdown pull-right`.
* The normal behavior when you click on the gear icon is to add the CSS class `open` to that div. This causes the submenu to be displayed.
* When the screen is small enough horizontally that the hamburger menu shows up, clicking on the gear icon no longer causes the CSS class `open` to show up.
* When I used the Chrome Dev Tools to add the class `open` to that div by hand while the screen was small, the submenu showed up.

Therefore, I conclude that the problem is somewhere in the `onClick` handling of the dropdown, probably in Bootstrap. Probably the Bootstrap CSS disables dropdown menus on small screens because they're inconvenient on smartphones, and we haven't implemented the correct replacement for those small screens.

**Comment by rmunn** [comment] 2017-08-29 10:10
Update: No, that's not it. What's going on is that when the screen is small enough, the hamburger menu shows up. The on-screen area dedicated to the hamburger menu, however, is quite large (see screenshot below), and overlaps with most of the gear-icon menu. On a desktop, I'm able to click on the very bottom of the gear-icon menu and make it trigger; however, on a smartphone, there isn't precise enough control of the click location to make that a good workaround.

![Area covered by hamburger menu](https://user-images.githubusercontent.com/90762/29815875-6610fee2-8cdc-11e7-9185-db9aa604bc52.png)

There are several possible solutions: shorten the horizontal area covered by that hamburger-menu element, or raise the z-order of the gear-icon menu, or lower the gear icon when the hamburger menu shows up, or possibly something else I haven't thought of yet. I'm inclined to the first option (narrow the horizontal space covered by the hamburger menu) since it's clearly not *supposed* to look that wide, but I'll look into it more tomorrow.

**Comment by megahirt** [comment] 2017-08-30 09:41
as it turns out, the hamburger menu and the profile picture are not clickable either... there must have been a change in the last 2 months that broke this.

**Comment by rmunn** [comment] 2017-08-31 03:01
That makes sense, and confirms that the overly-large `ul` element is responsible for this (since it also overlaps the hamburger menu and profile picture). So that's clearly the place to focus on to fix this issue.

**Comment by megahirt** [comment] 2017-08-31 13:32
This is now fixed on live.  Thank you @rmlockwood for reporting this!

**Closed by megahirt** 2017-08-31 13:32 UTC
