### ISSUE TITLE
Wrong data appearing after new project added

### ISSUE THREAD

**Issue by rmlockwood** [sillsdev/web-languageforge#148] opened 2017-08-13 16:03 UTC
I went to look at my Swedish dictionary in LF today and for some reason Kyrgyz data is showing up instead of Swedish. On Friday I added the Kyrgyz project and synced it with language depot. Not sure what is going on.

**Comment by megahirt** [comment] 2017-08-14 15:17
Strange.  Thanks for reporting it.  @rmunn can you look into this as soon as you are able?

**Comment by rmunn** [comment] 2017-08-15 04:40
I've been able to reproduce something very similar by making a copy of Ron's projects in my local Language Forge installation, though in the opposite "direction" -- I got Swedish words showing up when Kyrgyz should have shown up. I was able to verify that the actual data in the database has *not* been mixed between the two projects, so there is no data corruption going on here.

The actual cause, I think, is that we never designed Language Forge for use with two projects at once in two different tabs of the same browser. When someone works on a Language Forge project, we store a browser cookie that identifies the "current project". Then we use that cookie for future data transfers from the server to the browser (such as, for example, the word list that appears on the left-hand side of the word-editing view). However, browser cookies are stored per-browser, not per-tab. So if you load the Swedish project in tab 1, then load the Kyrgyz project in tab 2, the "current project" cookie will be updated with the Kyrgyz project's ID. If you then go back to the Swedish tab and hit Ctrl+R to refresh the page, you'd find yourself in the Kyrgyz project rather than the Swedish project -- but if you **haven't** refreshed the page, you'll still find Kyrgyz words showing up in the word list on the left side of the page, even though the top of the page still says that you're in the Swedish project. (That happens because the word list doesn't load all the words in the dictionary, for efficiency. Rather, it loads a "chunk" of about 50 words or so, then when you scroll down to near the end of the current "chunk", the next "chunk" of 50 words is loaded. At the time when a "chunk" of words is loaded, the "current project" browser cookie is used to know which project to fetch the next "chunk" from -- and that's how you can see Kyrgyz words in the Swedish project).

I'm afraid that fixing this bug is likely to take quite a long time, because the "current project" cookie is tied into a lot of our code and it would be a major change to rewrite most of those sections. (There isn't a quick-and-easy way to store a browser cookie in a per-tab basis; it would require a major reworking of our code and would not be easy). Since we probably won't have a solution for @rmlockwood's problem in the near future, there are two workarounds I can think of:

1. Only open one project at a time, going back to the main "Projects" list in Language Forge when you want to work with a different project. **Or**...
1. If it's necessary to work on two projects at once, use two different browsers (say, Chrome and Firefox) for the two different projects. This won't work very well for more than two projects (or three projects if you also use the Microsoft Edge browser), but it will at least allow you to access two projects at once without triggering this bug.

**Comment by megahirt** [comment] 2017-08-15 04:52
@rmunn Thank you for looking into this and for the very helpful explanation.  Does the problem clear up if the browser is refreshed?  Or has indexeddb become "corrupted" where it would need to be manually flushed...

As an addenum to option 2 in Robin's reply, you could use a Chrome incognito window or a Firefox private browsing tab to ensure that the cookies aren't cross pollinating.

**Comment by rmunn** [comment] 2017-08-15 08:32
Closing the browser tabs and re-opening them seems to have cleared up the problem, actually: I now have Swedish in one tab and Kyrgyz in another tab and I can only reproduce the problem by doing a Send/Receive in one of the tabs. Anything that doesn't do a Send/Receive (editing words, adding new words, etc.) doesn't mix up data between the projects: Language Forge is tracking them just fine. (I'm doing all this on my copies of Ron's projects, so that I won't be making any changes to his real projects).

So there may be a much simpler workaround than the one I suggested: just close the mixed-up tabs, then open new tabs and load Language Forge in those new tabs. It might only be the Send/Receive process that causes browser confusion, given that both @rmlockwood and I only saw this problem after a Send/Receive. (The process of starting a new project from data on Language Depot does a Send/Receive in the background, but skips the "Send" step since Language Forge doesn't yet have any changed data to send). And then, when doing a Send/Receive of any project, make sure you close any browser tabs that have other projects in them. As long as you close Language Forge tabs when doing a Send/Receive, and reopen them after the Send/Receive is complete, I think that should be enough to not encounter this bug.

**Comment by megahirt** [comment] 2017-08-15 10:09
Robin, but what is actually causing this condition to occur?  If you've
narrowed it down the bug only occurring after a S/R, how is the S/R
different?  It's good that we know how to avoid it, but it's still a bug
that we need to understand and fix.

**Comment by rmlockwood** [comment] 2017-08-15 12:40
I'm still getting this problem. I closed the tab and started a new tab. Same thing. I closed Chrome and restarted it. Same thing. When I open up LF in Edge it works fine. Here's an image of what I'm seeing: 
![image](https://user-images.githubusercontent.com/7088137/29316264-a68e2aaa-81c7-11e7-9678-fb786b80c1f1.png)

**Comment by megahirt** [comment] 2017-08-15 13:13
I suspect that your indexdb has become corrupt by this bug.  You can safely delete your indexdb in chrome dev tools under application.  Right now I don't have more specific instructions but I remember you've done this before.

On August 15, 2017, at 7:40 PM, R Lockwood <notifications@github.com> wrote:

I'm still getting this problem. I closed the tab and started a new tab. Same thing. I closed Chrome and restarted it. Same thing. When I open up LF in Edge it works fine. Here's an image of what I'm seeing:
￼

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.￼

{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/sillsdev/web-languageforge","title":"sillsdev/web-languageforge","subtitle":"GitHub repository","main_image_url":"<a href="https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png">https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png</a>","avatar_image_url":"<a href="https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png">https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png</a>","action":{"name":"Open in GitHub","url":"<a href="https://github.com/sillsdev/web-languageforge">https://github.com/sillsdev/web-languageforge</a>"}},"updates":{"snippets":[{"icon":"PERSON","message":"@rmlockwood in #148: I'm still getting this problem. I closed the tab and started a new tab. Same thing. I closed Chrome and restarted it. Same thing. When I open up LF in Edge it works fine. Here's an image of what I'm seeing: \r\n![image](<a href="https://user-images.githubusercontent.com/7088137/29316264-a68e2aaa-81c7-11e7-9678-fb786b80c1f1.png">https://user-images.githubusercontent.com/7088137/29316264-a68e2aaa-81c7-11e7-9678-fb786b80c1f1.png</a>)\r\n"}],"action":{"name":"View Issue","url":"<a href="https://github.com/sillsdev/web-languageforge/issues/148#issuecomment-322455472">https://github.com/sillsdev/web-languageforge/issues/148#issuecomment-322455472</a>"}}}

**Comment by megahirt** [comment] 2017-09-07 02:26
Closing this issue as @rmlockwood hasn't replied.  If this is still an issue please do re-open.  Thanks.

**Closed by megahirt** 2017-09-07 02:26 UTC
Labels: bug
