### ISSUE TITLE
bug: new user unable to sign in using oauth

### ISSUE THREAD

**Issue by alex-larkin** [sillsdev/web-languageforge#1238] opened 2021-11-05 20:26 UTC
**Describe the bug**
Pablo using his personal Gmail email address ([see Slack](https://sil-language-software.slack.com/archives/CGDKZ7NTV/p1636053848091200)) is unable to sign in and access my project. After creating an account with Google, he gets sent back to the homepage. He attempts to log in via Google, but again is sent back to the homepage. If he navigates manually to a URL inside the project, he is prompted to sign in with Google. Upon doing so, he's sent back to the homepage. 

**To Reproduce**
1. Sign in to Pablo's Gmail account (Billy and I have the creds, and you will likely need Pablo's help with 2-factor authentification)
2. Visit languageforge.org and sign in with his Google account
3. Notice that you are at [languageforge.org/#](languageforge.org/#)

**Expected behavior**
Since this is the first time accessing the project, he should be taken to https://languageforge.org/app/projects and see my project. 

**Screenshots**
Links to images and videos in Slack:
[Computer](https://sil-language-software.slack.com/archives/CGDKZ7NTV/p1636132631092500?thread_ts=1636053848.091200&cid=CGDKZ7NTV)
[Cell](https://sil-language-software.slack.com/archives/CGDKZ7NTV/p1636132661092900?thread_ts=1636053848.091200&cid=CGDKZ7NTV)
[Computer Info](https://sil-language-software.slack.com/archives/CGDKZ7NTV/p1636132674093200?thread_ts=1636053848.091200&cid=CGDKZ7NTV)
[Chrome Browser Info](https://sil-language-software.slack.com/archives/CGDKZ7NTV/p1636132686093700?thread_ts=1636053848.091200&cid=CGDKZ7NTV)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome (up-to-date), Firefox (up-to-date)

**Mobile (please complete the following information):**
 - Device: Uncertain
 - OS: Android
 - Browser: Chrome

**Android App in Google Play**
For Mobile, are you using the Language Forge Android app in the Google Play store?  [Yes/No]

**Additional context**
He was previously invited to the project many months ago but had done nothing. I removed and readded his permission, but saw no change of behavior. 

### What doesn't work

- Pablo using OAuth with Pablo's personal Gmail account, on his laptop, using Chrome or Firefox
- Pablo using OAuth with Pablo's personal Gmail account, on his cellphone, using Chrome 
- Billy using Pablo's OAuth, on Billy's computer

### What does work

- Pablo using another Gmail account in Chrome on his laptop
- Alex using his account in Chrome on Pablo's laptop

**Comment by alex-larkin** [comment] 2021-11-05 20:27
Robin wrote in Slack:

 I just checked the /app/siteadmin page (which you wouldn't have access to) and discovered that his user account has been created but is in a disabled status. When I tried to enable it it complained that the Full Name field (which is currently blank) was not filled out. @Alex Larkin, if you can give me the correct way to spell his full name, I can put that into the site admin page, and then it should allow me to enable his account.
With some time spent investigating, I might be able to figure out why his account ended up disabled (my first guess is the auto-translation to Spanish did something that prevented the login routine from completing normally, but I can't prove that without a whole lot of effort). But I can probably get this fixed right now with 5 minutes' work, I just need to know what his full name should be on the account.

**Comment by alex-larkin** [comment] 2021-11-05 20:29
Summary of Slack conversation: 

1. Billy supplied Robin with Pablo's full name. 
2. Robin added it in the site admin page. 
3. Robin speculated: "Probably the invitation process got short-circuited by the failure. Shouldn't be an issue to just re-add him to the project."
4. We are now awaiting word from Pablo to see if it worked.

**Comment by alex-larkin** [comment] 2021-11-05 20:30
To investigate: Is this a bug that needs fixing, or a one-off? @longrunningprocess @rmunn what do you think?

**Comment by longrunningprocess** [comment] 2021-11-05 23:12
I definitely think this needs some closure... either we need better error handling for something like this or we need to ensure it's not possible to get into this state in the first place.

**Comment by rmunn** [comment] 2021-11-06 09:23
First step is to reproduce this somehow. We'll need to try adding different users with different methods, to see if they are all working. E.g., if the user goes through the Signup process, vs. if the project admin invites him via an email link, that sort of thing.

Problems: It's better to be doing this kind of testing on qa.languageforge.org, but there are OAuth problems on qa.languageforge.org that we can't resolve right now. Basically, Chris and I have both lost access to the Google OAuth settings for the Language Forge project, so we can't edit the authorized OAuth return URLs. We've tried reaching out to the SIL people who have the Google admin access for this, but hit some roadblocks around personnel availability and time zone issues. So until we can get the Google OAuth credentials unstuck so that Chris and I (and we'd want to add Billy as well) can actually edit the Google OAuth settings, any such testing would have to be done on the live server, which already has hundreds of user accounts and is not ideal for testing.

**Comment by alex-larkin** [comment] 2021-11-06 22:13
Thank Robin for weighing in. Maybe we could to try to reach out to the SIL personnel again?

**Comment by alex-larkin** [comment] 2021-11-06 22:14
Good news from Pablo. He reports that he was able to log in. He said that he explored around a bit and that LF has a nice user interface! 

Next week I'll meet with him to explore a bit more.

Thanks guys!

**Comment by rmunn** [comment] 2021-11-08 08:50
Excellent. I'll close this bug since we fixed the issue for the user who was having trouble. If there's a deeper issue where some code paths lead to an unsuccessful signin experience, a different issue should be opened to track that, with fictional users instead of having a real person's details used in the issue.

**Closed by rmunn** 2021-11-08 08:50 UTC
Labels: bug, research, triage
