### ISSUE TITLE
Share button is visible on non-project pages and shows empty dialog

### ISSUE THREAD

**Issue by longrunningprocess** [sillsdev/web-languageforge#1099] opened 2021-08-24 16:51 UTC
![image](https://user-images.githubusercontent.com/4412848/130657082-a4535a38-0a47-4fa8-b361-820f1ae25fa6.png)

click on Share button anywhere except a specific project page to cause this failure... looks like this fails in current production as well, maybe this button shouldn't be visible all the time.  @megahirt Was the original intent for this button to only be used from a project page?

**Comment by megahirt** [comment] 2021-08-25 03:47
You are right @longrunningprocess this is a bug.  The share button should only be visible from a project page (at least that is how it was intended).  I think we could populate the Share button with something useful on other pages with more thought and design, but as it stands right now, it's just a project thing.

This bug is fixed when the share button is hidden on non-project pages.  An example of a button hidden on non-project pages is the project settings Cog button.

**Comment by megahirt** [comment] 2022-09-23 07:34
closing as duplicate of #1241

**Closed by megahirt** 2022-09-23 07:34 UTC
