### ISSUE TITLE
feat: delete user account

### ISSUE THREAD

**Issue by JeanneSon** [sillsdev/web-languageforge#1362] opened 2022-03-29 04:06 UTC
## Description
The user does not have the possibility to delete their account. 

## Suggested solution
Provide this functionality.

### Quick fix
Currently, users need to contact the dev team via email to request a manual deletion of their account. It would be helpful to describe this procedure and put the email address on the /app/userprofile page.

### In the long run
There should be a button enabling the user to delete their account without the manual work of the dev team.

## Screenshot: Where the user probably misses this functionality
![image](https://user-images.githubusercontent.com/43119728/160530407-52a341a0-bc5d-45c4-b6e0-a48a104471e1.png)

**Comment by megahirt** [comment] 2022-03-29 04:36
This is a good suggestion.  Let's start by adding this to the functional
spec document under "user profile".

**Comment by palmtreefrb** [comment] 2022-10-06 13:11
- [ ]  what are the manual deletion steps for removing a user.
- [ ]  can the user and activity just be set to **active=false** thus preserving history and allowing re-activation.
- [ ]  never worked with php. where in the project is user and activity php code etc?

**Comment by megahirt** [comment] 2022-10-07 07:07
@palmtreefrb good questions.  I don't think I've deleted a user in a long time, if ever.  That partially what this card is about, to make the task easy.

In PHP, there is the [UserModel->remove() function](https://github.com/sillsdev/web-languageforge/blob/develop/src/Api/Model/Shared/UserModel.php#L195-L196) which simply removes the user from project membership and then deletes the user object.

This method is too simplistic because there are several other places in our database where we have userRefs e.g. the activity objects all have userRefs.  A project also has an ownerRef which is an user Id.  How would we handle deleting an owner?

I have searched the codebase, and the only real usage of UserModel->remove() is a public static function [UserCommands::deleteUsers()](https://github.com/sillsdev/web-languageforge/blob/develop/src/Api/Model/Shared/Command/UserCommands.php#L146).  This is theoretically used in the admin app where it is theoretically possible to delete an user.

But be warned!  If we actually did delete an user, we would almost certainly leave dangling references to that user littered in the project and activity database.  That would probably cause the application to throw exceptions or break client-side.  So it's dangerous to actually delete an user in the current system.

So that's also what this card is about - we need a proper way to "remove" that preserves our application's data integrity.

**Comment by megahirt** [comment] 2022-10-07 07:26
I would suggest searching for "userref" case-insensitive in VSCode and you will see where all of our userRefs are throughout the code base.

Here's a partial screenshot of the results on my local vscode
![image](https://user-images.githubusercontent.com/3444521/194496642-32baa9ac-5f73-4ec4-a283-609f43764433.png)

**Comment by megahirt** [comment] 2022-10-28 16:10
@palmtreefrb what is the status of your work on this issue?  Thanks for any update.

**Comment by palmtreefrb** [comment] 2022-10-28 17:03
I still have several weeks of PHP training before I want dive into the code. We never worked with PHP in our organization. Mostly Angular and C# .net

**Comment by megahirt** [comment] 2022-10-28 17:07
OK, so you plan to tackle this issue after you complete some PHP tutorials, correct?  Thank you for the status update.  If you could also post your status/standup in Slack at least once a week, that would be really helpful for me and the team to see where you're at.  Thanks for your help and work on this!

**Comment by laineyhm** [comment] 2023-01-06 06:30
> @palmtreefrb good questions. I don't think I've deleted a user in a long time, if ever. That partially what this card is about, to make the task easy.
> 
> In PHP, there is the [UserModel->remove() function](https://github.com/sillsdev/web-languageforge/blob/develop/src/Api/Model/Shared/UserModel.php#L195-L196) which simply removes the user from project membership and then deletes the user object.
> 
> This method is too simplistic because there are several other places in our database where we have userRefs e.g. the activity objects all have userRefs. A project also has an ownerRef which is an user Id. How would we handle deleting an owner?
> 
> I have searched the codebase, and the only real usage of UserModel->remove() is a public static function [UserCommands::deleteUsers()](https://github.com/sillsdev/web-languageforge/blob/develop/src/Api/Model/Shared/Command/UserCommands.php#L146). This is theoretically used in the admin app where it is theoretically possible to delete an user.
> 
> But be warned! If we actually did delete an user, we would almost certainly leave dangling references to that user littered in the project and activity database. That would probably cause the application to throw exceptions or break client-side. So it's dangerous to actually delete an user in the current system.
> 
> So that's also what this card is about - we need a proper way to "remove" that preserves our application's data integrity.

For deleting owners, one idea could be to prevent an owner from deleting their account until they have deleted all projects they are an owner of, or have transferred ownership of their owned projects to another member. What do you think @megahirt ?

For activity objects, what is the expected behavior? Do we want the member's name to show up next to their actions, even after deleting their account, for other members who are still a part of the project to be able to see?

**Comment by megahirt** [comment] 2023-01-06 07:33
>For deleting owners, one idea could be to prevent an owner from deleting their account until they have deleted all projects they are an owner of, or have transferred ownership of their owned projects to another member. What do you think?

@laineyhm Yes!

Prevent deletion if they own any project (ask them to transfer ownership first)

Delete user account should:
- automatically remove user from all projects
- remove all PII from the user model, including name, username, etc.
- replace the name and username fields with the userId (long string)
- replace the avatar image to a question mark, I think we already have something like this checked in

**Closed** 2023-01-17 13:51 UTC
Labels: feature
