### ISSUE TITLE
Override input systems for gloss for contributor makes the gloss field disappear

### ISSUE THREAD

**Issue by rmlockwood** [sillsdev/web-languageforge#164] opened 2017-09-13 14:45 UTC
I have a project called Latin. I as the manager set one of my users as contributor and I set the gloss field in the View Settings as having overridden input systems where I just want the French input system to be shown instead of all of them. I keep Show Field ticked. When I do this the contributor doesn't see the gloss field at all. It seems the doing the override Input Systems make it go away.

**Comment by rmunn** [comment] 2017-09-14 02:59
Do you know if the Gloss field was set to "Hidden if empty" in the project's configuration? (Settings menu -> Configuration -> Fields tab). If the Gloss field was set to "Hidden if empty", that would explain the behavior you're seeing: the gloss may have had data in other input systems, but now that it is only showing the French input system, there is no *visible* data and so the field is hidden because it appears empty. (The data for the other input systems has not been lost, but since it's not being presented to the user, it's not being considered for the "Hidden if empty" logic).

**QUESTION:** There are two possible ways for us to implement the "Hidden if empty" logic. Which one of these would be how you would expect it to work?

1. The "Hidden if empty" logic considers *all* input systems, whether or not they're visible.
2. The "Hidden if empty" logic considers *only* visible input systems.

 I.e., let's say you have Latin, French, and English input systems in your project, and the Gloss field is configured to be "Hidden if empty", and to show only the French input system. Let's also say that for one word, the Gloss field has data in English but not in French. With approach 1, the Gloss field would be visible, but seem empty (because only the French writing system is visible). With approach 2, the Gloss field would not be shown at all.

We chose approach 2, because we thought that approach 1 would confuse users, who would think "I know I checked the "Hidden if empty" box, so why is this empty field still showing up?" Since the English writing system is not currently visible, it's not obvious why the Gloss field is showing up despite all the visible fields being empty. But what do you think? Would approach 1 or approach 2 seem more intuitive to you?

Also, if you check the Configuration settings for the Gloss field and find that "Hidden if empty" is turned **OFF**, then there's clearly a bug. If the Gloss field has "Hidden if empty" turned **ON**, then the site is currently working as designed, and we should close this bug report. (Though we would be open to a feature request saying "I would like it to work differently", of course). So if the Gloss field is **NOT** set to "Hidden if empty" in your project, please let us know so that we can classify this report as a bug. Thanks!

**Comment by rmlockwood** [comment] 2017-09-14 08:32
The Gloss field was not set to "Hidden if empty". With it on or off I get the same behavior that the gloss field doesn't show for the contributor.

**Comment by rmlockwood** [comment] 2017-09-14 08:36
I think approach 2 is good. We don't want to confuse users like you described.

**Comment by ThomasBlok** [comment] 2017-12-04 03:30
Issue moved to https://jira.sil.org/browse/LF-17

**Closed by ThomasBlok** 2017-12-04 03:30 UTC
Labels: bug
